.github/workflows/release-please.yml

Adds the release-please action for automated npm publishing flow.

chore: add release-please action

---

deno/bundle.ts
src/formats/javascript.ts

Updates bootstrap layer version.

feat: update bootstrap to 6270f39aacac8b000a2f84f4

---

.github/workflows/release-please.yml
.github/workflows/workflow.yml

Runs the CI matrix sequentially, in an attempt to diagnose https://github.com/netlify/edge-bundler/issues/23.

chore: set up Deno in release-please workflow

---

deno/bundle.ts
src/formats/javascript.ts

updates the bootstrap layer to https://github.com/netlify/edge-functions-bootstrap/commit/527a3300eeb50025acfe7a0711bcc3cc485997b0, cc https://github.com/netlify/log-drains/issues/271#issuecomment-1129801582

Update bootstrap to ef-bootstrap@527a33

---

src/bundler.ts
test/bundler.ts

Removes the use eszip feature flag.
Closes: [#51](https://github.com/netlify/edge-bundler/issues/51) 
**Checklist**
- [] The status checks are successful (continuous integration). Those can be seen below.

feat: remove feature flag eszip

---

deno/bundle.ts
src/formats/javascript.ts

Bump bootstrap to version 1.0.0

feat: bump edge bootstrap to 1.0.0

---

.github/CODEOWNERS

Replacing @netlify/compute with @netlify/runtime-pod-compute
This relates to https://github.com/netlify/pod-compute/issues/89

chore: Update CODEOWNERS file

---

deno/bundle.ts
src/formats/javascript.ts

This has to do with https://github.com/netlify/pod-compute/issues/159
**Checklist**

feat: update bootstrap url

---

test/bridge.ts

Better assertion for the sometimes failing tests.

chore: fix tests with environment variables

---

node/package_json.ts
package-lock.json
package.json
test/package_json.ts

With #117, the internal directory structure changed and therefore the relative location of `package.json` has changed. This PR changes `getPackageVersion` so that it can find `package.json` regardless of the relative path.

fix: fix `getPackageVersion`

---

node/formats/javascript.ts

Updating to latest version of bootstrap
Getting https://github.com/netlify/cli/issues/4655 ready for production

feat: update bootstrap latest to use latest version of bootstrap

---

node/formats/javascript.ts

see title
includes the feature that adds the path to the log message
https://github.com/netlify/pod-compute/issues/211

feat: Update bootstrap url to latest version

---

.eslintrc.cjs
node/config.ts
node/declaration.ts
node/manifest.test.ts
node/manifest.ts
test/fixtures/with_config/netlify/edge-functions/user-func3.ts
test/fixtures/with_config/netlify/edge-functions/user-func4.ts

Removes the `mode` configuration property in favour of a `cache` property that can be either `off` or `manual`.

feat!: replace `mode` property with `cache`

---

deno/lib/common.ts

part of https://github.com/netlify/pod-compute/issues/279

fix: log when module loading fails after max tries

---

node/formats/javascript.ts

fix: update to newer version of bootstrap: 636e17c6f5c1ed0008150054

---

node/formats/javascript.ts

Updating bootstrap to v 63760359c1267a000900d7fb

fix: update bootstrap to 63760359c1267a000900d7fb

---

node/bundle_error.ts
node/bundler.test.ts
node/formats/eszip.ts
node/formats/javascript.ts
node/npm_import_error.ts
test/fixtures/imports_npm_module/functions/func1.ts

Closes https://github.com/netlify/pod-compute/issues/287

feat: add detection + nice error message for npm import errors

---

node/formats/javascript.ts

Please make sure the title is clear and descriptive.
If you are fixing a typo or documentation, please skip these instructions.
Otherwise please fill in the sections below.
Example: I'm always frustrated when [...]
Example: This fixes #5012
Example: I've fixed this by [...]
**Describe alternatives you've considered**
Example: Another solution would be [...]
**Checklist**

fix: update bootstrap to 637b7052e167bb00082f54f1

---

node/formats/javascript.ts

fix: update bootstrap to 637cf7ce9214b300099b3aa8

---

node/declaration.test.ts
node/declaration.ts

Please make sure the title is clear and descriptive.
If you are fixing a typo or documentation, please skip these instructions.
Otherwise please fill in the sections below.
Example: I'm always frustrated when [...]
This relates to https://github.com/netlify/pod-compute/issues/292
Example: I've fixed this by [...]
**Describe alternatives you've considered**
Example: Another solution would be [...]
**Checklist**

fix: deep merge in source and toml config

---

node/server/server.ts

Closes https://github.com/netlify/pillar-runtime/issues/372.

feat: remove `--unstable` flag from `serve` flags

---

node/formats/javascript.ts

feat: update bootstrap version

---

node/bundler.ts
node/feature_flags.ts
node/manifest.test.ts
node/manifest.ts

Wraps the logic introduced by #298 in a feature flag.

feat: wrap regex validation in feature flag

---

node/validation/manifest/__snapshots__/index.test.ts.snap
node/validation/manifest/index.test.ts
node/validation/manifest/schema.ts

I added a new field in this pr: https://github.com/netlify/edge-bundler/pull/304
But didn't realise I also had to add it to the validator. Thus, now I have this pr!

chore: add generator to manifest validation

---

node/bundler.test.ts
node/bundler.ts
node/config.test.ts
node/feature_flags.ts

chore: clean some default feature flags

---

node/downloader.test.ts
package-lock.json
package.json

The test now takes ~2s instead of ~22s
Also update vitest

chore: improve speed of downloader test

---

node/manifest.test.ts

adds a small reproduction case for some customer behaviour

fix: add repro for customer case

---

.github/workflows/github-packages-releaser.yml
.github/workflows/release-please.yml
package.json

connected to: https://github.com/netlify/pod-compute/issues/490

feat: add npm provenance

---

.eslintrc.cjs
node/bridge.test.ts
node/bundler.test.ts
node/config.test.ts
node/downloader.test.ts
node/downloader.ts
node/formats/javascript.ts
node/main.test.ts
node/stage_2.test.ts
node/types.test.ts
package-lock.json
package.json
test/integration/test.js

The package can be replaced by `fs.rm`
ref: https://github.com/netlify/cli/issues/5699

fix: remove del package

---

node/formats/eszip.ts
node/import_map.test.ts
node/import_map.ts

The current implementation of the `ImportMap` class is too complex to understand and too hard to extend.
I've extended the tests and I'll also add inline comments to add some colour to some of the changes.
This is an internal change, so no customer-facing behaviour should change.

feat: simplify `ImportMap`

---

node/declaration.test.ts
node/declaration.ts
node/feature_flags.ts
node/manifest.test.ts
node/manifest.ts

Reverts netlify/edge-bundler#560

fix: revert "feat: transform negative lookaheads"
