netlify/edge-bundler

src/server/server.ts

When the `certificatePath` option is supplied to the `serve` method, Edge Bundler will call `deno run` with the `--cert` flag.
Part of https://github.com/netlify/pillar-runtime/issues/323.

feat: allow certificate to be supplied to `serve`

---

src/manifest.ts
test/manifest.ts

This PR changes the regular expressions generated from a `path` declaration so that they contain an optional trailing slash.
So `/foo` will yield `^/foo/?$` instead of `^/foo$`.

feat: add trailing slash to regular expressions

---

src/server/server.ts

Adding flag to deno runtime in server startup to disable code gen from strings in order to mimic production environment and throw errors on usage of eval() and new Function() operations.
See also [https://github.com/netlify/pillar-runtime/issues/272](https://github.com/netlify/pillar-runtime/issues/272)
Added flag as suggested in comments in above issue and verified against a local test function.  The test function I used was
```
export default (req, context) => {
const func = new Function("a", "b", 'return a + " " + b');
console.log(eval('func("hello", "world")'));
};
```
I deployed this to a production site and got the following errors: …

chore: add flag to disable code gen from strings

---

.github/workflows/update-bootstrap-deploy-id.yml

This PR adds a GH Actions workflow that opens a PR to update the Edge Bootstrap Deploy ID. I plan to either use a `deploy-succeeded` Netlify hook to call this workflow, or to call it from a GH workflow in edge-functions-bootstrap.
cc https://github.com/netlify/edge-bundler/pull/43#issuecomment-1153822651

chore: deploy id automation

---

src/bridge.ts

The lifecycle hooks can return a Promise according to the TS types. In order to not get out of order execution we should await them.

fix: await lifecycle hooks as they might return promises

---

.eslintrc.cjs
src/bridge.ts
src/bundler.ts
src/server/server.ts
src/types.ts
test/types.ts

As part of https://github.com/netlify/pillar-runtime/issues/322, we'd like customers to start importing the types from `https://edge.netlify.com` rather than `netlify:edge`. To ensure that they always have the latest version of that specifier, and not an outdated version cached by Deno CLI, this PR adds a new `ensureLatestTypes` function that will:
1. Hit the `/version.txt` endpoint exposed by https://github.com/netlify/edge-functions-bootstrap/pull/57 to see what is the latest version of the types
2. Check a `types-version.txt` file locally to see whether the cache was already refreshed for that version
3. If not, run `deno cache -r https://edge.netlify.com` to update the specifier in the Deno CLI cache
`ensureLatestTypes` runs on both `bundle` and `serve`, and any errors resulting from …

feat: refresh types on Deno CLI cache

---

.eslintrc.cjs
.github/workflows/update-bootstrap-deploy-id.yml
deno/bundle.ts
src/bridge.ts
src/bundler.ts
src/formats/eszip.ts
src/formats/javascript.ts
src/import_map.ts
src/types.ts
test/bundler.ts
test/fixtures/helper.ts
test/fixtures/project_1/functions/func1.ts

Adds support for import maps when bundling to ESZIP.
Also starts loading the bootstrap layer from https://edge.netlify.com.
Builds on top of https://github.com/netlify/edge-functions-bootstrap/pull/60.
Closes https://github.com/netlify/pod-compute/issues/145.

feat: add support for import maps when bundling ESZIP

---

src/bundler.ts
test/bundler.ts
test/fixtures/helper.ts
test/fixtures/project_1/functions/func1.ts

Adds a new `basePath` property to the `bundle` function. When present, that is used instead of the default "common path" approach.

feat: accept `basePath` parameter

---

src/bridge.ts
src/bundler.ts
src/feature_flags.ts
test/bundler.ts

Adds a `denoDir` parameter to the `bundle` function. When set, its value is used to set the `DENO_DIR` environment variable.
https://github.com/netlify/pod-compute/issues/161

feat: add support for `denoDir` parameter

---

src/bridge.ts
src/bundler.ts
src/logger.ts
src/server/server.ts
src/types.ts
test/logger.ts
test/main.ts
test/types.ts

With https://github.com/netlify/build/issues/3220 in the pipeline, we'll be able to capture debug data into our system logs without polluting customer builds logs. This PR takes advantage of that and introduces an optional `logFunction` to both `bundle` and `serve`, which is then used instead of `console.log` to print logs.
When this is in place, Netlify Build will be able to pass along the `systemLog()` utility, which was introduced in https://github.com/netlify/build/pull/4406.

feat: add support for system logger

---

src/bridge.ts
src/logger.ts
test/main.ts

In #85, the `DenoBridge` constructor requires a `logger` parameter, since a default is not offered. This breaks https://github.com/netlify/cli/pull/4900, since CLI is using `DenoBridge` directly and it's not passing in a logger.
This PR makes the `logger` parameter optional and uses a default logger if one is not supplied.

feat: use default logger in DenoBridge

---

src/bridge.ts
src/server/server.ts
test/bridge.ts
test/main.ts

This is a prerequisite for https://github.com/netlify/cli/issues/4614.
The PR allows setting environment variables in `deno.run` and `deno.runInBackground` as well as disabling extending of current runtime environment variables. These two options basically are plain `execa` options, which are forwarded to execa.
I disabled the extending of env variables in the DenoServer so that once the CLI sets the variables it will be only those available in deno. With the exception of `DENO_DIR`. `DENO_DIR` is okay to have locally?

feat: allow setting environment variables and disable extending in DenoServer

---

package-lock.json
package.json
src/bridge.ts

PR #82 broke the detection of global installed binaries. The detection of the binary uses all environment variables and finds the global binary. When we then run the edge function with `deno ...` deno is not found because PATH is not there anymore.
I don't like this solution, but I like the alternative even less. The only alternative i could come up is using `node-which` package to find the absolute path to the global binary. But not sure if we really want to add that overhead?
What do you think? This means that edge functions in dev will have PATH available.

fix: ensure PATH is always set

---

deno/bundle.ts
deno/lib/common.ts
deno/lib/consts.ts
deno/lib/stage2.ts

When bundling an edge function with the ESZIP format, Edge Bundler is fetching some logic from the edge bootstrap in order to generate the stage 2 file. In reality, this logic has very little to do with the bootstrap layer itself and is actually concerned with bundling, so it makes sense to move it to Edge Bundler.
By moving it, we're also reducing the number of network calls we need to make at build time, which are causing occasional errors.

feat: inline stage 2 ESZIP bundler

---

common/stage2.ts
deno/bundle.ts
deno/lib/stage2.ts
package-lock.json
package.json
src/formats/eszip.ts
src/import_map.ts
test/bundler.ts
test/import_map.ts

Support for import maps was limited when producing ESZIP bundles, because thee loader function wasn't being called for specifiers that looked like relative file paths, and therefore those were not respecting the import map.
With this PR, we're using native support for import maps in https://deno.land/x/eszip@v0.28.0 rather than resolving them ourselves in the loader function.
**NOTE**: Netlify Build will need to start sending a `baseURL` property with the path of the import map file itself ([here](https://github.com/netlify/build/blob/856e361f9b6646469ca8752598f0e486fc3c5b4a/packages/build/src/plugins_core/edge_functions/index.js#L59)), so that we know how to resolve any relative paths in the import map.
Closes https://github.com/netlify/edge-bundler/issues/108.

feat: add support for import maps with ESZIP

---

node/formats/eszip.ts
node/package_json.ts

Another follow up to #117! 😓 
Similarly to #118, we were also hardcoding the relative path to the Deno bundler. This PR uses the package path to compute it instead.

fix: use right location for Deno bundler

---

node/formats/javascript.ts
test/node/stage_2.ts

Same as #122 but for the stage 2 file used in local development.

feat: export `metadata` object in local stage 2

---

deno/lib/stage2.ts
node/formats/javascript.ts
package.json
test/deno/stage2.test.ts
test/node/stage_2.ts

Follow up to #122 and #126, which haven't been released yet (see #125). It changes the shape of the `metadata` object to have function-specific metadata under a `functions` key.
_Before:_
```ts
export const metadata = {
func1: {
url: "file:///some/path/func1.ts"
},
func2: {
url: "file:///some/path/func2.ts"
}
}
```
_After:_
```ts
export const metadata = {
functions: {
func1: {
url: "file:///some/path/func1.ts"
},
func2: {
url: "file:///some/path/func2.ts"
}
}
}
```
This will allow us to more easily export additional metadata that is not tied to a specific function (e.g. the path of the stage 2 file).

feat: add `functions` level to `metadata` object

---

node/formats/eszip.ts
node/formats/javascript.ts
node/server/server.ts
test/node/bundler.ts
test/node/stage_2.ts

Adds the `--no-config` flag to the bundling and serving commands. This prevents any user-land configuration files from influencing our internal implementation.
Closes #127.

fix: run `deno` with `--no-config`

---

test/integration/test.js

When the integration test runs in a release branch, the version returned by `npm info` is no longer the version we're looking to test. Instead, we want to pull that version from `package.json`.

chore: fix version lookup in integration test

---

deno/config.ts
node/config.ts

Follow-up to #133. We need the `--allow-net` flag when running the `config` function, otherwise remote specifiers cannot be resolved.

fix: use `allow-net` flag to run `config` function

---

node/finder.ts

Adds support for .jsx and .tsx entrypoints in edge functions
Deno includes out of the box support for jsx and tsx. However edge bundler doesn't recognise these files, so they can't be used for edge functions at the moment. This PR adds .tsx and .jsx to the list of allowed extensions. It allows things like this:
```tsx
import React from "https://esm.sh/react@18";
import { renderToReadableStream } from "https://esm.sh/v96/react-dom@18.2.0/deno/server.js";
export default async function handler(req: Request) {
const url = new URL(req.url);
const username = url.searchParams.get("username");
if (!username) {
url.searchParams.set("username", "netlify");
return Response.redirect(url.toString(), 302);
}
const …
```

feat: support JSX and TSX in edge functions

---

.eslintrc.cjs
node/bundler.ts
node/config.test.ts
node/config.ts
test/fixtures/with_config/.netlify/edge-functions/framework-func1.ts
test/fixtures/with_config/.netlify/edge-functions/framework-func2.ts
test/fixtures/with_config/netlify/edge-functions/user-func1.ts
test/fixtures/with_config/netlify/edge-functions/user-func2.ts

#133 added support for a `config` export, which we evaluate at build time to extract a configuration object. Currently, we're not using any import maps when doing this invocation, any specifiers that we can't process (even if they're not used by the `config` function itself) will throw an error.
This PR addresses that by evaluating the `config` export with the same import maps as the runtime evaluation.

fix: use import maps in config evaluation

---

node/config.test.ts
node/config.ts
node/declaration.ts
node/manifest.test.ts
node/manifest.ts
test/fixtures/with_config/netlify/edge-functions/user-func3.ts
test/fixtures/with_config/netlify/edge-functions/user-func4.ts

Looks for a `mode` property in a function declaration (either in the TOML or in-source) and if its value is `after_cache`, the route is added to `post_cache_routes` instead of `routes` in the manifest file. This makes the function run after the cache.
Internal: https://github.com/netlify/pod-compute/issues/208

feat: add support for post-cache routes

---

node/config.ts
test/fixtures/with_config/netlify/edge-functions/user-func1.ts

When invoking the edge function at build time to resolve the `config` export, we should call the Deno CLI with `--allow-env`, otherwise we'll get an error if the function is trying to access `Deno.env` in the global scope.

fix: run `config` export with `--allow-env`

---

node/server/server.test.ts
node/server/server.ts
test/fixtures/serve_test/echo_env.ts

To make in-source configuration work with the CLI, we need to parse the function config when in server mode. This PR enables that.

feat: get config in server mode

---

node/server/server.ts

Deno version 1.27.1 does not work with this flag and as it turned out it was introduced to disallow `eval()` in dev/cli, because it wasn't allowed in prod. 
Now eval() is available in prod so we should remove this flag.

fix: remove disallow-code-generation-from-strings flag

---

node/bundler.test.ts
node/feature_flags.ts
node/formats/eszip.ts

flag is fully rolled out: https://github.com/netlify/edge-bundler/pull/187#issue-1441699898

fix: remove flag edge_functions_use_vendored_eszip

---

node/bundler.ts
node/layer.ts
node/manifest.test.ts
node/manifest.ts

Adds a new `layers` optional parameter to the `bundle` entry point, which writes custom layer information to the manifest.
Support for the `local_url` property and the `serve` entry point will come in a separate PR.

feat: add support for custom layers

---

deno/lib/consts.ts
deno/lib/stage2.ts
node/bundler.test.ts
node/bundler.ts
test/fixtures/with_layers/functions/func1.ts

This should've been part of #198, but I forgot. We need to tell the ESZIP loader to treat any specifiers that start with `layer:` as dangling imports.

feat: add `layer:` prefix to ESZIP loader

---

deno/config.ts
node/config.test.ts
node/config.ts

Please make sure the title is clear and descriptive.
If you are fixing a typo or documentation, please skip these instructions.
Otherwise please fill in the sections below.
Example: I'm always frustrated when [...]
This fixes https://github.com/netlify/pod-compute/issues/249
Example: I've fixed this by [...]
**Describe alternatives you've considered**
Example: Another solution would be [...]
**Checklist**

feat: validate edge function signature at build time

---

node/bundler.test.ts
node/bundler.ts
node/config.test.ts
node/declaration.test.ts
node/declaration.ts
node/deploy_config.test.ts
node/deploy_config.ts
node/import_map.ts
node/server/server.ts
node/utils/error.ts
test/fixtures/with_config/.netlify/edge-functions/config.json
test/fixtures/with_config/.netlify/edge-functions/import_map.json
test/fixtures/with_deploy_config/.netlify/edge-functions/config.json
test/fixtures/with_deploy_config/.netlify/edge-functions/func2.ts
test/fixtures/with_deploy_config/.netlify/edge-functions/import_map.json
test/fixtures/with_deploy_config/netlify/edge-functions/func1.ts
test/fixtures/with_deploy_config/util.ts
test/fixtures/with_import_maps/functions/config.json
test/fixtures/with_import_maps/functions/import_map.json
test/fixtures/with_layers/functions/config.json

Framework-generated functions are currently configured using a `manifest.json` file placed in the `.netlify/edge-functions` internal directory (documented [here](https://docs.netlify.com/edge-functions/create-integration/#generate-declarations)). This file is currently [loaded and parsed in Netlify Build](https://github.com/netlify/build/blob/main/packages/build/src/plugins_core/edge_functions/lib/internal_manifest.js) and then its contents are supplied to Edge Bundler via the `declarations`, `layers` and `importMaps` properties.
This PR moves that logic to Edge Bundler, such that the `bundle` entry point receives an optional `configPath` property which indicates the path to this internal configuration file. I've called this `configPath` and …

feat!: move internal config file to Edge Bundler

---

node/bundler.test.ts
node/bundler.ts
node/config.test.ts
node/feature_flags.ts
node/formats/javascript.ts
node/server/server.ts
test/fixtures/invalid_functions/functions/func1.ts
test/integration/test.js

We've been generating ESZIP bundles for all sites for a while now. This PR formally removes support for JavaScript bundles.

feat!: remove support for JavaScript bundles

---

deno/lib/stage2.ts
node/bundle.ts
node/bundler.test.ts
node/bundler.ts
node/config.test.ts
node/formats/eszip.ts
node/import_map.test.ts
node/import_map.ts
node/manifest.ts
package-lock.json
package.json
shared/consts.ts
test/fixtures/helper.ts
test/fixtures/with_config/.netlify/edge-functions/import_map.json
test/fixtures/with_config/helper.ts
test/fixtures/with_import_maps/functions/func1.ts
test/fixtures/with_import_maps/functions/import_map.json
test/fixtures/with_import_maps/helper.ts
test/integration/test.js
test/util.ts

Import maps aren't working as expected at the moment for a couple of reasons.
First of all, we're not setting the `import_map_url` property in the isolate config, because we're not even writing that to the manifest.
Also, we're writing absolute paths (from the host machine in the build system) into the import map, instead of converting those to ESZIP paths using the virtual root prefix.
This PR addresses that.
Closes https://github.com/netlify/pod-compute/issues/313.

feat: save import map URL to manifest

---

node/bundler.test.ts
node/validation/manifest/__snapshots__/index.test.ts.snap
node/validation/manifest/index.test.ts
node/validation/manifest/schema.ts

Follow up to https://github.com/netlify/edge-bundler/pull/239, where the schema said `importMapURL` as the key name instead of `import_map` which is correct.

fix: correct import_map attribute name in validation

---

node/bundler.test.ts
node/formats/eszip.ts

Adds a safeguard for when the edge functions dist directory is not a child of the root directory.

fix: add guard for import map with extraneous dist directory

---

deno/bundle.ts
deno/lib/stage2.ts
node/bundle.ts
node/bundler.test.ts
node/bundler.ts
node/config.test.ts
node/formats/eszip.ts
node/import_map.test.ts
node/import_map.ts
node/manifest.ts
node/server/server.ts
shared/consts.ts
shared/stage2.ts
test/fixtures/with_import_maps/functions/func1.ts
test/fixtures/with_import_maps/functions/import_map.json
test/fixtures/with_import_maps/helper.ts
test/util.ts

In #235 we started writing the import map URL to the manifest. We were writing an actual import map file to disk, to the dist directory, and then building a virtual path relative to the repository root.
For example, the following project would yield a path of `file:///root/.netlify/edge-functions-dist/import_map.json` for the import map.
```
.netlify/
edge-functions-dist/
import_map.json
other-file
```
While this works great for projects with this structure, it doesn't work that well when the dist directory is not a child directory of the repository root, because we won't be able to encode a relative path into the file URL (e.g. something like `file:///root/../../import_map.json` is not valid).
What happens now in these situations is that we …

feat: use `netlify:import-map` specifier

---

node/import_map.test.ts
node/import_map.ts

We're writing import map files to disk so that integrations like the VSCode plugin can pick them up. In https://github.com/netlify/edge-bundler/pull/235 we started resolving these paths relative (by passing an argument to `getContents()`), but that's a bad idea because we're not surfacing the repository root, and so we're resolving them with the wrong base.
This PR reverts that, such that import maps written to a file get absolute paths.

fix: do not transform paths when writing import map to disk

---

.eslintrc.cjs
node/bundler.test.ts
node/bundler.ts
node/deno_config.test.ts
node/deno_config.ts
node/server/server.test.ts
node/server/server.ts
package-lock.json
package.json
test/fixtures/serve_test/.netlify/edge-functions/greet.ts
test/fixtures/serve_test/.netlify/edge-functions/import_map.json
test/fixtures/serve_test/deno.json
test/fixtures/serve_test/helper.ts
test/fixtures/serve_test/import_map.json
test/fixtures/serve_test/netlify/edge-functions/echo_env.ts
test/fixtures/with_import_maps/deno.json
test/fixtures/with_import_maps/import_map.json
test/fixtures/with_import_maps/user-functions/func2.ts

Currently, the only way to use import maps with edge functions is by placing an import map file inside the internal edge functions directory, which is meant for integrations.
This PR adds support for user-defined import maps by looking for a [Deno configuration file](https://deno.land/manual@v1.28.3/getting_started/configuration_file) at `/deno.json` or `/deno.jsonc`. When this file is found and it contains an `importMap` property, we load that import map into the existing flow.
Closes https://github.com/netlify/pod-compute/issues/206

feat!: add support for user-defined import maps

---

node/bundler.test.ts
node/bundler.ts
node/feature_flags.ts

Follow-up to #256. Adds a feature flag around the logic that reads the Deno config.

feat: read Deno config behind feature flag

---

node/bundler.test.ts
node/import_map.ts
test/util.ts

Fixes a bug in #265 that prevents additional import map paths from being read when one points to a non-existing file.

fix: read other import map paths when one doesn't exist

---

node/bundler.test.ts
node/npm_import_error.ts
test/fixtures/imports_npm_module_scheme/functions/func1.ts

We're already printing a nice error message for npm imports. We should do the same for `npm:`-prefixed imports.
discovered in https://netlify.slack.com/archives/C02BUDF7A4B/p1671250384449859

fix: print nice npm error message for npm: specifier as well

---

deno/config.ts
node/config.test.ts
node/config.ts
test/fixtures/serve_test/netlify/edge-functions/echo_env.ts
test/fixtures/with_config/.netlify/edge-functions/framework-func1.ts
test/fixtures/with_config/netlify/edge-functions/user-func1.ts
test/fixtures/with_config/netlify/edge-functions/user-func3.ts
test/fixtures/with_config/netlify/edge-functions/user-func4.ts

Changes the `config` export to expect a plain object instead of a function that returns an object.
https://github.com/netlify/pod-compute/issues/323#issuecomment-1360564040

feat!: make `config` export a plain object

---

node/bundler.test.ts
node/bundler.ts
node/config.test.ts
node/config.ts
node/declaration.ts
node/manifest.test.ts
node/manifest.ts
node/validation/manifest/schema.ts
test/fixtures/with_config/netlify/edge-functions/user-func5.ts

Accompanies https://github.com/netlify/stargate/pull/1343. We found that having `excluded_patterns` inside of `routes` doesn't cut it, so we're moving it into a new `function_config` field.
- https://github.com/netlify/stargate/pull/1343
- https://github.com/netlify/pillar-runtime/issues/615
- https://github.com/netlify/netlify-server/pull/2557

feat: move excluded_patterns into function_config

---

node/validation/manifest/schema.ts

We're currently printing the warning `strict mode: missing type "array" for keyword "items" at "#/properties/function_config" (strictTypes)`. This PR fixes that. Apparently `items` is restricted to use with `type: "array"`, the equivalent is `additionalProperties: ...` (which is the same as `properties: { ".*": ... }`.

fix: replace "items" with "additionalProperties"

---

node/formats/javascript.ts
node/server/server.test.ts

Part of https://github.com/netlify/partner-deno/issues/11. This renames `x-deno-` headers to `x-nf-` headers.
Tests fail right now, but will pass once https://github.com/netlify/edge-functions-bootstrap/pull/155 lands.

feat: rename x-deno- to x-nf- headers

---

node/declaration.ts
node/manifest.test.ts
node/manifest.ts
package-lock.json
package.json

This PR parses into an AST any paths defined as regular expressions and:
1. Throws an error if they contain negative lookaheads, as they aren't supported by the Go engine
2. Converts named captured groups into regular captured groups, since the JavaScript syntax for named captured groups is different than the one used by the Go engine
Supersedes #226.

feat: validate pattern declarations

---

.github/workflows/workflow.yml

See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ for context.

chore: migrate to Github Action's output files

---

node/declaration.ts
node/manifest.test.ts
node/manifest.ts

Allows edge function to have a generator field in the manifest. It adds generator to the Declaration, which is the config that plugins write and then forwards this generator field to the edge manifest.
Work on https://github.com/netlify/pod-compute/issues/415

feat: add generator field to edge function manifest

---

node/formats/javascript.ts

chore: fix typo

---

node/manifest.ts

This fixes a problem where a config block for a function that doesn't have a declaration throws an error, because `manifestFunctionConfig[name]` will be `undefined`. This PR adds a check for that.

fix: ignore config blocks for undefined functions

---

.github/workflows/workflow.yml
node/validation/manifest/__snapshots__/index.test.ts.snap
package-lock.json
package.json
vitest.config.ts

This updates vitest and changes the workflow to use 14.18.0 as the minimum version we test with.
Fixes #318

chore: update vitest and test with node 14.18.0 as minimum

---

node/__snapshots__/declaration.test.ts.snap
node/bundler.ts
node/declaration.test.ts
node/declaration.ts
node/feature_flags.ts

This changes the order of edge functions to
1. Framework functions defined in `manifest.json` (if the functions have ISC the info will overwrite settings from manifest.json)
2. Framework functions not defined in `manifest.json` but that have ISC
3. User functions defined in TOML (if the functions have ISC the info will overwrite settings from manifest.json)
4. User functions not defined in TOML but have ISC.
Fixes: https://github.com/netlify/pod-compute/issues/442

fix: change the order of how edge functions are written to the manifest

---

node/feature_flags.ts
node/validation/manifest/__snapshots__/index.test.ts.snap
node/validation/manifest/index.test.ts
node/validation/manifest/index.ts
node/validation/manifest/schema.ts

Adjust the validation message as proposed in #339

fix: revert slash validation and change validation message

---

node/declaration.test.ts
node/declaration.ts

Runs the regular expressions through the `RegExp` constructor to ensure that they are properly escaped, rather than handling the escaping ourselves.
Supersedes #376.

fix: ensure regular expressions are properly escaped

---

node/manifest.test.ts
node/manifest.ts
test/util.ts

Adds a `getRouteMatcher` utility method to the tests, which lets us grab a manifest and test specific routes against it.
It also adds a specific test case that we were looking to understand the current support for.

chore: add route matcher to tests

---

node/bundler.ts
node/config.test.ts
node/config.ts
node/feature_flags.ts
node/server/server.ts

fix: remove FF edge_functions_invalid_config_throw

---

.github/workflows/integration.yml
.github/workflows/workflow.yml
deno/lib/stage2.ts
node/bridge.ts
node/bundler.test.ts
test/fixtures/imports_node_specifier/netlify/edge-functions/func1.ts

Adds support for Node built-ins via specifiers with the `node:` prefix. It works by marking those specifiers as externals, which lets Deno handle them internally.
https://deno.com/blog/node-builtins-on-deploy

feat: support `node:` prefix

---

node/bridge.ts
node/downloader.ts

- A small note about the deno version.
- Add even handlers before calling `pipe()`
- log errors to system log when `getBinaryVersion` fails

fix: improvements to download process of deno

---

.github/workflows/workflow.yml
node/bridge.ts
package-lock.json
package.json

- vitest 0.32 changed the default coverage provider from c8 to v8, so let's use it.
- I also I noticed that coverage wasn't even enabled on CI.
- Also split up workflows to not run lint on every arch, it is enough to run it once on latest lts version of Node.js
- Noticed that the tests do not work, because the minimum version for deno is `1.30`, but the bootstrap is using features of deno `1.31+` https://github.com/netlify/edge-functions-bootstrap/commit/fa7e337bb903be575f5bab2c3501546d64c9c73f#diff-619f5f90a26baa69bacaaf654cbdf11eddc272ad34226a796112e3a1ec64d24bR2 //cc @Skn0tt 
- the tests though failed completely with deno `1.31`, so I set the minimum to `1.32` which now works
- test deno `1.32` (the minimum) as well as the latest version of deno

chore: use vitest v8 coverage provider  and enable coverage

---

node/declaration.test.ts
node/declaration.ts

Through https://netlify.slack.com/archives/C0183KVDHFH/p1690359798528619?thread_ts=1690283461.628349&cid=C0183KVDHFH, we discovered that we don't document that regex patterns need to be enclosed in `^...$`. But we validate on it:
https://github.com/netlify/edge-bundler/blob/db1f51edb7f312022910ae3f13d0e6b9a9d21f30/node/validation/manifest/index.ts#L19-L24
We could either add this requirement to our documentation, or automatically enclose patterns that don't have the `^...$`. I believe the latter is better DX. This PR implements that.

fix: ensure patterns match on whole path

---

deno/config.ts
node/bundler.ts
node/config.test.ts
node/config.ts
node/server/server.test.ts
node/server/server.ts
test/fixtures/serve_test/netlify/edge-functions/global_netlify.ts

When a function accesses `globalThis.Netlify`, the scanning for function config currently fails because it's not defining `globalThis.Netlify`.
This PR fixes that.

fix: parseConfig stumbling over `globalThis.Netlify` usage in global scope

---

node/manifest.test.ts
node/manifest.ts

See https://netlify.slack.com/archives/C05556LEX28/p1691397875723719?thread_ts=1690966905.287929&cid=C05556LEX28.

fix: mark invalid url patterns as user error

---

node/config.test.ts
node/manifest.test.ts
node/manifest.ts
node/validation/manifest/schema.ts

Adds a `path` property to the manifest file containing the original path defined for the function, before any transformations to regular expressions.
Part of https://github.com/netlify/pod-dev-foundations/issues/459.

feat: add `path` to manifest

---

node/config.test.ts
node/feature_flags.ts
node/manifest.test.ts
node/manifest.ts
package-lock.json
package.json

Removes the feature flag added in https://github.com/netlify/edge-bundler/pull/392, which has now been fully rolled out.
The `URLPattern` format is now a requirement for https://github.com/netlify/pod-dev-foundations/issues/459.

feat: remove `URLPattern` feature flag

---

deno/lib/consts.ts
deno/lib/stage2.ts
node/import_map.test.ts
node/import_map.ts
test/fixtures/with_config/netlify/edge-functions/user-func1.ts

Adds support for loading the types from the `@netlify/edge-functions` specifier. Support for `netlify:edge` is maintained for backwards-compatibility.
Closes https://github.com/netlify/pod-dev-foundations/issues/417.

feat: support `@netlify/edge-functions` specifier

---

node/config.test.ts
node/config.ts
node/declaration.ts
node/manifest.ts
node/validation/manifest/schema.ts
test/fixtures/with_config/netlify/edge-functions/user-func4.ts
test/fixtures/with_config/netlify/edge-functions/user-func5.ts

Part of https://github.com/netlify/pod-dev-foundations/issues/579.

feat: match on http methods

---

deno/config.ts
node/bundler.ts
node/config.test.ts
node/config.ts
node/server/server.ts

We've seen problems with using a non-pinned version of `edge.netlify.com`, since Deno appears to sometimes seems to combine files from cache with fresh files from `edge.netlify.com`. Since `edge.netlify.com` isn't immutable, that can lead to clashes - the fresh files are incompatible with the older cached files.
To ensure this doesn't happen, this PR pins down the bootstrap deploy that's used to infer the config.
To reduce complexity, I didn't just update the default value, bot removed the possibility to inject the version altogether. This ensures CLI and Buildbot behave the same, when they're on the same version of edge-bundler, making debugging a little easier.
Related to https://github.com/netlify/cli/pull/5936.

fix: pin bootstrap version used in config extraction

---

deno/bundle.ts
node/bundle_error.ts
node/bundler.test.ts

Closes https://github.com/netlify/pod-dev-foundations/issues/580.

fix: hide stack trace on syntax errors

---

node/bundler.test.ts
node/bundler.ts
node/feature_flags.ts
node/import_map.test.ts
node/import_map.ts
node/npm_dependencies.ts
shared/consts.ts
test/fixtures/imports_npm_module/functions/func1.ts
test/fixtures/imports_npm_module/helper.ts
test/fixtures/imports_npm_module/import_map.json

This is a follow-up to #454 addressing a couple of issues I found when testing this in production.
The main change is that the esbuild plugin needs to be aware of user-defined import maps, otherwise it will fail to resolve specifiers that have been remapped.
I ended up making other changes, which I'll describe using inline comments.

fix: support import maps in npm module resolution

---

node/bundler.test.ts
node/formats/eszip.ts
node/npm_dependencies.ts
node/npm_import_error.ts
test/fixtures/imports_npm_module/functions/func1.ts

This is a follow-up to #454. With the goal of cutting scope for the initial release, this PR removes support for the `npm:` prefix, letting users load npm modules only when using an un-prefixed bare specifier.
This is because using the `npm:` prefix involves supporting the module version as part of the specifier, which requires additional work. We might still add this, but we may decide to exclude it from the initial release.
Part of https://github.com/netlify/pod-dev-foundations/issues/578.

feat: remove support for `npm:` prefix

---

node/bridge.ts
node/bundler.ts
node/logger.test.ts
node/logger.ts
node/server/server.ts

We should handle logging within the entrypoints of our systems, not within the satellite packages. This PR allows injecting a logging provider for user-facing logs.

feat: allow injecting user-facing logger

---

node/finder.ts

We're supporting `.mjs` files in Netlify Functions, so we should do the same for Edge Functions.
I'm not adding `.cjs` here, since Edge Functions need to be ES Modules.

fix: detect .mjs files

---

node/bundler.test.ts
node/npm_dependencies.ts
test/fixtures/imports_npm_module/functions/func1.ts

When we try detecting imported NPM modules, we use ESBuild. Right now, it sometimes fails that tracing process because of code-level errors. One specific example for that is top-level await, which is only available in ES Modules. This PR fixes this specific instance by switching the bundling format for NPM modules tracing from the (default) CJS format to ESM.

fix: NPM bundling should use ESM format

---

node/npm_dependencies.ts

Parsing NPM modules might fail. We already have a user-facing log line for that, so we don't need ESBuild's output on top of it. This PR mutes esbuild, and directs the generated warnings and errors to system logs.

fix: mute esbuild while parsing for NPM modules

---

node/bundler.test.ts
node/bundler.ts
node/feature_flags.ts
node/formats/eszip.ts
node/manifest.test.ts
node/manifest.ts
node/npm_import_error.ts
node/server/server.test.ts
node/server/server.ts

Some housekeeping! We've rolled out both flags and have no intention of rolling them back. Let's remove them! Also changing the error we're throwing to a user error.

fix: remove npm_modules and fail_unsupported_regex flags

---

node/npm_dependencies.ts
test/fixtures/imports_npm_module/node_modules/child-1/index.js
test/fixtures/tsx/functions/func1.tsx

When bundling an NPM package that does `import { Buffer } from "node:buffer"`, like `@netlify/blobs`, then edge-bundler was outputting both the unchanged import from said package, plus another import via the Banner added in #519. Here's an excerpt for how the output looks:
```js
...
import {Buffer} from "node:buffer";
import {createRequire as ___nfyCreateRequire} from "node:module";
import {fileURLToPath as ___nfyFileURLToPath} from "node:url";
import {dirname as ___nfyPathDirname} from "node:path";
let __filename=___nfyFileURLToPath(import.meta.url);
let __dirname=___nfyPathDirname(___nfyFileURLToPath(import.meta.url));
let require=___nfyCreateRequire(import.meta.url);
// test/fixtures/imports_npm_module/node_modules/child-1/index.js
import { Buffer } from "buffer";
...
```
Those two …

fix: prevent global namespace clash for `Buffer`

---

node/server/server.test.ts
node/server/server.ts

During local dev, the import map paths can change after startup. For example when a framework generates an import map after the dev server was already initiated. So we can't know all the paths up-front!
Currently, edge-bundler needs us pass all of them at startup. But it doesn't need them until invocation time.
This PR moves the import map parameter from startup time to invocation time, so we don't have to work around this in the CLI.

feat!: provide import maps when starting the isolate, not server

---

node/declaration.test.ts
node/declaration.ts
node/feature_flags.ts
node/manifest.test.ts
node/manifest.ts

When processing a declaration pattern, transforms negative lookaheads into a set of exclusion patterns.
Supersedes #451. Part of FRA-195.

feat: transform negative lookaheads

---

node/feature_flags.ts
node/manifest.test.ts
node/manifest.ts

As we add a PCRE-compatible regular expression engine to our edge nodes, we must stop transforming regular expressions in Edge Bundler to make them compatible with the RE2 engine. We're doing this behind a feature flag.
Part of https://linear.app/netlify/issue/FRA-195/devise-strategy-to-handle-nextjs-routing-matchers.

feat: support PCRE regexp engine

---

node/bridge.ts
node/server/server.test.ts
node/server/server.ts
test/fixtures/monorepo_npm_module/packages/frontend/functions/func1.ts

By default, the process that is spawned to run Deno in the serve mode will pipe the stderr and stdout to the corresponding descriptors of the parent process.
However, in some cases it's useful to be able to specify a different destination, such as when running tests and capturing output in a file on disk. To achieve that, this PR introduces two new parameters to the `serve` entry point that allow consumers to specify custom stderr and stdout.
If these parameters are not specified, the descriptors of the parent process continue to be used, so no breaking changes are being introduced.

feat: allow custom `stderr` and `stdout` in server

---

node/declaration.test.ts
node/declaration.ts
node/manifest.ts

This is a follow-up to #563. When using PCRE, we're currently skipping all of the logic in `parsePattern`, which isn't correct. We want to keep the logic that encloses the expression in `^` and `$` characters.
Part of FRA-195.

fix: enclose regexp when using PCRE

---

node/bridge.ts

Fixes a regression in #564 where the `pipeOutput` property is no longer being passed correctly.

fix: pipe log output in server

---

node/declaration.test.ts
node/declaration.ts
node/feature_flags.ts
node/manifest.test.ts
node/manifest.ts
package-lock.json
package.json

Removes the feature flag introduced in #563 which has been fully rolled out.

feat: remove feature flag for PCRE engine
